### PR TITLE
stuff to save Vram to less then 7gb (not  done)

### PR DESCRIPTION
**Pull request by Manni1000**
I added dynamic unloading and loading of the main model and the VAE to save VRAM.
I also added Int8Quantized to save VRAM.
I also added a button in the Gradio UI to select the low VRAM mode (Int8Quantized).

When this is active, the model runs with under 7GB VRAM. A lot more people will be able to use it like this.

!!!!! But this is not completely done. The button does not work!!! A variable in the pipeline.py (Quantization = True) file currently changes if it is active. Maybe someone else can connect the button logic with the variable; I am currently not able to do it. But I published this so others can play around with it.

### CODE REVIEW

**Comment by Manni1000** [comment]
oh i have to fix something with the vae encoding but i will do that tomorrow.

**Comment by cocktailpeanut** [comment]
@Manni1000 sir there are thousands of us waiting for this to get merged....

**Comment by Manni1000** [comment]
I will fix the vae buck today :)

**Comment by Manni1000** [comment]
ok now everything  works. but because of the chages in the main branch its not compatible

**Comment by nitinmukesh** [comment]
I tested from your fork, 
https://github.com/Manni1000/OmniGen/

Doesn't work.
The Gradio WebUI is launched. I enter prompt and click generate.
During first launch all models are downloaded fine. After that a lot of RAM usage as expected and than hands at Loading safetensors, no activity in GPU VRAM which should happen as soon as safetensor loading starts. Please could you check, I will test from your repo only.

**Comment by Manni1000** [comment]
Maby fist try generating a image without a input image just as a test.

**Comment by nitinmukesh** [comment]
> Maby fist try generating a image without a input image just as a test.

This was without image only. Tried first example where there is only prompt and no image and 512 x 512.

**Comment by nitinmukesh** [comment]
I am using your repository only, not this one for testing.
https://github.com/Manni1000/OmniGen/

If you guide me how to ignore any commit or give command to clone. (BTW not a developer)

**Comment by codingdudecom** [comment]
I can't get this to work either, I tried it on Kaggle, it says:


Loading safetensors
Quantizing weights to 8-bit...
  0%|          | 0/50 [00:00<?, ?it/s]
  0%|          | 0/50 [00:01<?, ?it/s]
OutOfMemoryError

OutOfMemoryError: CUDA out of memory. Tried to allocate 2.12 GiB. GPU 0 has a total capacity of 14.74 GiB of which 848.12 MiB is free. Process 2413 has 13.91 GiB memory in use. Of the allocated memory 11.64 GiB is allocated by PyTorch, and 2.15 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management

**Comment by SunDeveloper777** [comment]
Install with Pinokio and raplace this files. Work with 5-9 gb VRAM
[27-10-2024.zip](https://github.com/user-attachments/files/17533620/27-10-2024.zip)

**Comment by nitinmukesh** [comment]
@SunDeveloper777 

Thank you. Is it possible to use outside pinokio. Like cloning your repository or this repo and then by replacing files.

**Comment by SunDeveloper777** [comment]
Thank you. Is it possible to use outside pinokio. Like cloning your repository or this repo and then by replacing files.https://github.com/SunDeveloper777/OmniGen-Forge27.10.2024, 14:08, "nitinmukesh" ***@***.***>:
@SunDeveloper777
Thank you. Is it possible to use outside pinokio. Like cloning your repository or this repo and then by replacing files.

**Comment by codingdudecom** [comment]
not for me though :-(

I'm still trying to get this working on Kaggle

first I'm getting "The error AttributeError: module 'torch.library' has no attribute 'register_fake' typically arises when using PyTorch, particularly in versions where this function is either not available or incorrectly referenced."  (totch verion 2.3.1)

Thought I need to upgrade, so I did, but now I get this error:

"AttributeError: partially initialized module 'torchvision' has no attribute 'extension' (most likely due to a circular import)"

why is this so complicated to run? the space on Huggingface gives an error 3 out of 4 tries also... I'm finding very difficult to evaluate this model to be honest

**Comment by cocktailpeanut** [comment]
@Manni1000 please check the PR i sent to your fork. I guess this PR will work once you merge my PR to your fork https://github.com/Manni1000/OmniGen/pull/2

**Comment by cocktailpeanut** [comment]
Also, I confirm it works (with my fix applied). Took 1min 56sec on a 4090.

BTW shouldn't we make LOW VRAM option checked by default? I mean, this thing is practically unusable without the low vram option.

**Comment by ayttop** [comment]
not work on colab t4

**Comment by iwr-redmond** [comment]
The @cocktailpeanut  PR is working on Ubuntu 22.04:

remote="https://github.com/peanutcocktail/OmniGen"
local=/opt/local-venvs/omnigen
git clone $remote $local
cd $local/
python -m venv venv
source venv/bin/activate
pip install -e .
pip install gradio spaces
python app.py

Tick the new 'Low VRAM (8-bit quantization) ' button. Basic t2i maxes out at 5.8GB VRAM. Done right quick!

**Comment by Qarqor5555555** [comment]
ram=???

**Comment by Qarqor5555555** [comment]
It needs more than 12 ram ,,,,,,Can you convert it and store it... Can you upload the conversion code only... Can you upload the converted model... Any solution you can come up with, please... I want to use it on 12 gb ram like Colab T4

**Comment by iwr-redmond** [comment]
15.9GB system RAM. Possibly a scooch too much for Colab.
